import { Hono } from "hono";

const app = new Hono();

app.get("/", async (c) => {
  const html = `<!DOCTYPE html>
		<body>
    <div>	 m	  <h1>Hello World</h1>
		  <p>This markup was generated by a Cloudflare Worker.</p><div/>
		
		</body>`;

  return new Response(html, {
    headers: {
      "content-type": "text/html;charset=UTF-8",
    },
  });
});

export default app;
